protocols = imap
listen = *
mail_location = maildir:/var/mail/%d/%n
namespace inbox {
  inbox = yes
  separator = /
  mailbox Drafts { special_use = \Drafts auto = subscribe }
  mailbox Junk { special_use = \Junk auto = subscribe }
  mailbox Sent { special_use = \Sent auto = subscribe }
  mailbox Trash { special_use = \Trash auto = subscribe }
  mailbox Archive { special_use = \Archive auto = subscribe }
}

auth_mechanisms = plain login
disable_plaintext_auth = no
passdb { driver = passwd-file args = scheme=SHA512-CRYPT username_format=%u /etc/dovecot/users }
userdb { driver = static args = uid=vmail gid=vmail home=/var/mail/%d/%n }
service auth { unix_listener auth-userdb { mode = 0666 } }
log_path = /dev/stderr
info_log_path = /dev/stdout
